---
title: "Analisis de la felicidad europea 2002-2014"
author: "Maria Isabel Gamez Salazar"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
    source_code: embed 
runtime: shiny
---

```{r setup, include=FALSE}

library(flexdashboard)
library (ggplot2)
library (flexdashboard)
library (tidyverse)
library (maps)
library (DT)
library (shiny)
library(shinydashboard)
library (dplyr)
library (here)
library (gridExtra)
install.packages("knitr")

```

```{r}
file_path <- "/Users/mariaisabelgamezsalazar/BDS2024/data/m8datoslimpios.csv"
m8datos_limpios <- read.csv(file_path)

```
Column {.sidebar data-width=150}
-----------------------------------------------------------------------
```{r}
selectInput("pais_sel", "Selecciona un país", choices = c('TODOS', sort(unique(m8datos_limpios$cntry))), selected='TODOS')
selectInput("year_sel", "Selecciona año", choices = c('TODOS', sort(unique(m8datos_limpios$year))), selected='TODOS')
selectInput("genero_sel", "Selecciona género", choices = c('TODOS', "1", "2"), selected='TODOS')
selectInput("health_sel", "Selecciona nivel de salud", choices = c('TODOS', sort(unique(m8datos_limpios$health))), selected='TODOS')

filtered_data <- reactive({
  data <- m8datos_limpios
  if (input$pais_sel != 'TODOS') {
    data <- data[data$cntry == input$pais_sel, ]
  }
  if (input$year_sel != 'TODOS') {
    data <- data[data$year == input$year_sel, ]
  }
  if (input$genero_sel != 'TODOS') {
    data <- data[data$gndr == input$genero_sel, ]
  }
  if (input$health_sel != 'TODOS') {
    data <- data[data$health == input$health_sel, ]
  }
  data
})
```


Column {data-width=500}
-----------------------------------------------------------------------

### Evolucion de la felicidad 2002-2014

```{r}
renderPlot({
  data <- filtered_data()
  if(nrow(data) == 0) return(NULL)
  
  avg_happy <- data %>%
    group_by(cntry, year) %>%
    summarize(mean_happy = mean(happy, na.rm = TRUE))
  
  custom_palette <- c("#999999", "#56B4E9", "#0072B2", "#E69F00", "#D55E00",
                      "#CC79A7", "#8B4513", "#B2DF8A", "#33A02C", "#FB9A99",
                      "#E31A1C", "#6A3D9A", "#FFFF99", "#F0E442", "#00CED1")
  
  ggplot(avg_happy, aes(x = year, y = mean_happy, color = cntry, group = cntry)) +
    geom_smooth(method = "loess", se = FALSE, size = 1) +
    scale_x_continuous(breaks = seq(2002, 2014, by = 2), limits = c(2002, 2014)) +
    scale_y_continuous(limits = c(0, 10)) +
    labs(title = "Promedio de felicidad por país y año",
         x = "Año",
         y = "Promedio de puntuación de felicidad",
         color = "País") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          legend.position = "bottom") +
    scale_color_manual(values = custom_palette)
})
```
### Mapa de la felicidad media

```{r}
renderPlot({
  library(maps)
  library(mapdata)
  
  media_felicidad <- m8datos_limpios %>%
    group_by(cntry) %>%
    summarise(mean_happy = mean(happy, na.rm = TRUE))
  
  paises_seleccionados <- c("BE", "CH", "DE", "DK", "ES", "FI", "FR", "GB", "HU", "IE", "NL", "NO", "PL", "PT", "SE")
  media_felicidad <- media_felicidad %>% filter(cntry %in% paises_seleccionados)
  
  europe_map <- map_data("world", region = c("Belgium", "Switzerland", "Germany", "Denmark", "Spain", "Finland", "France", "United Kingdom", "Hungary", "Ireland", "Netherlands", "Norway", "Poland", "Portugal", "Sweden"))
  
  europe_map <- europe_map %>%
    mutate(region = recode(region, `UK` = "GB", `Sweden` = "SE", `Finland` = "FI", `France` = "FR", `Spain` = "ES",
                           `Belgium` = "BE", `Switzerland` = "CH", `Germany` = "DE", `Denmark` = "DK",
                           `Hungary` = "HU", `Ireland` = "IE", `Netherlands` = "NL", `Norway` = "NO",
                           `Poland` = "PL", `Portugal` = "PT", `Sweden` = "SE"))
  
  europe_happiness <- merge(europe_map, media_felicidad, by.x = "region", by.y = "cntry")
  
  ggplot(data = europe_happiness, aes(x = long, y = lat, group = group, fill = mean_happy)) +
    geom_polygon(color = "white") +
    coord_fixed(1.3) +
    scale_fill_viridis_c(option = "plasma", name = "Media de Felicidad", na.value = "grey50") +
    labs(title = "Nivel de felicidad en Europa (2002-2014)",
         caption = "Fuente: Encuesta ESS") +
    theme_minimal() +
    theme(
      plot.background = element_rect(fill = "white"),
      panel.background = element_rect(fill = "white"),
      axis.text = element_text(color = "black"),
      axis.title = element_text(color = "black"),
      plot.title = element_text(color = "black"),
      panel.grid.major = element_line(color = "grey", size = 0.5),
      panel.grid.minor = element_blank()
    )
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Relacion felicidad y tiempo total de visualizacion de tv
```{r}
renderPlot({
  data <- filtered_data()
  if (nrow(data) == 0) return(NULL)
  
  ggplot(data, aes(x = tvtot, y = happy)) +
    geom_smooth(method = "lm", se = TRUE, color = "blue") +  # Línea de regresión con intervalo de confianza
    scale_y_continuous(limits = c(6, 8)) +
    labs(title = "Relación entre felicidad y horas totales de televisión",
         x = "Horas totales de televisión (tvtot)",
         y = "Puntuación de felicidad") +
    theme_minimal()
})


```
### Relacion felicidad y salud
```{r}


renderPlot({
  data <- filtered_data()
  if (nrow(data) == 0) return(NULL)
  
  data <- data %>%
    mutate(gndr = recode(gndr, `1` = "Male", `2` = "Female")) %>%
    filter(!is.na(health) & !is.na(happy))
  
  ggplot(data, aes(x = health, y = happy, color = gndr, group = gndr)) +
    stat_summary(fun = mean, geom = "line", size = 1.2) +
    stat_summary(fun = mean, geom = "point", size = 3) +
    scale_color_manual(values = c("Male" = "blue", "Female" = "pink")) +
    labs(title = "Interacción entre género y salud en la felicidad",
         x = "Nivel de salud",
         y = "Felicidad",
         color = "Género") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
})

```

```{r}

```

